#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/xaga

PRODUCT_COPY_FILES += \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/ae/mt6895/ParameterDB_ae.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/ae/mt6895/ParameterDB_ae.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/af/mt6895/ParameterDB_af.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/af/mt6895/ParameterDB_af.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/awb/mt6895/ParameterDB_awb.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/awb/mt6895/ParameterDB_awb.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/awbsync/mt6895/ParameterDB_awbsync.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/awbsync/mt6895/ParameterDB_awbsync.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/feature/mt6895/ParameterDB_feature.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/feature/mt6895/ParameterDB_feature.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/flash/mt6895/ParameterDB_flash.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/flash/mt6895/ParameterDB_flash.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/flashcali/mt6895/ParameterDB_flashcali.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/flashcali/mt6895/ParameterDB_flashcali.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/mt6895/ParameterDB.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/mt6895/ParameterDB.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/mt6895/top_control_data.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/mt6895/top_control_data.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/pd/mt6895/ParameterDB_pd.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/pd/mt6895/ParameterDB_pd.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/pipeline/mt6895/ParameterDB_pipeline.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/pipeline/mt6895/ParameterDB_pipeline.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tone/mt6895/ParameterDB_tone.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tone/mt6895/ParameterDB_tone.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mt6895/ISP_info.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mt6895/ISP_info.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagagc02m1_mipi_raw/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagagc02m1_mipi_raw/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagagc02m1_mipi_raw/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagagc02m1_mipi_raw/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagagc02m1_mipi_raw_3/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagagc02m1_mipi_raw_3/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagagc02m1_mipi_raw_3/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagagc02m1_mipi_raw_3/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov02b10_mipi_raw/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov02b10_mipi_raw/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov02b10_mipi_raw/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov02b10_mipi_raw/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov02b10_mipi_raw_3/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov02b10_mipi_raw_3/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov02b10_mipi_raw_3/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov02b10_mipi_raw_3/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_2/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_2/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_2/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_2/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_3/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_3/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_3/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_3/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_4/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_4/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_4/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagaov16a1_mipi_raw_4/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_2/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_2/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_2/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_2/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_3/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_3/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_3/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_3/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_4/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_4/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_4/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5k4h7_mipi_raw_4/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_2/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_2/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_2/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_2/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_3/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_3/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_3/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_3/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_4/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_4/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_4/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5kgw1_mipi_raw_4/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5khm2_mipi_raw/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5khm2_mipi_raw/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5khm2_mipi_raw/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5khm2_mipi_raw/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5khm2_mipi_raw_3/mt6895/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5khm2_mipi_raw_3/mt6895/ISP_mapping.db \
    vendor/xiaomi/xaga/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5khm2_mipi_raw_3/mt6895/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/xagas5khm2_mipi_raw_3/mt6895/ISP_param.db \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/FV-SAM-MTKXX.dat:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/FV-SAM-MTKXX.dat \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/PlaybackVolAna_CeRegion_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_CeRegion_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/PlaybackVolDigi_CeRegion_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_CeRegion_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/tfa98xx_music.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/tfa98xx_music.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/tfa98xx_ringtone.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/tfa98xx_ringtone.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/audio_param/tfa98xx_voice.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/tfa98xx_voice.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_hifi3.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/CFR_para_HD.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_HD.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/CFR_para_M.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_M.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/CFR_para_T.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_T.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/CFR_para_UW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/CFR_para_W.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/ai_scene.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ai_scene.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/almalence_sr_params_UW_upscale.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_UW_upscale.config \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/almalence_sr_params_tele.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_tele.config \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/almalence_sr_params_wide.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/almalence_sr_params_wide.config \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/anc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/anc.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/apu_miai_preview.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/apu_miai_preview.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/cal_w_uw_L16_golden_108m:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cal_w_uw_L16_golden_108m \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/cal_w_uw_L16_golden_64m_i:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cal_w_uw_L16_golden_64m_i \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/cal_w_uw_L16_golden_64m_ii:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cal_w_uw_L16_golden_64m_ii \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/deblur_sd_opencl_binary.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_sd_opencl_binary.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/deblur_sd_opencl_params.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_sd_opencl_params.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/deblur_txt_apu.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_txt_apu.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/ldc/intsense_config_undistort.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ldc/intsense_config_undistort.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/ldc/ldc_cap_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ldc/ldc_cap_cache \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/ldc/ldc_cap_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ldc/ldc_cap_model \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/ldc/ldc_cap_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ldc/ldc_cap_policy \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/miai_psn_config.yaml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/miai_psn_config.yaml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/mibokeh_mt6873_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_mt6873_opencl.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/mibokeh_mt6873_parameter.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_mt6873_parameter.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/quantize_mtk_0.00246_1800-360620_singleinput_bs1_1285.dla:$(TARGET_COPY_OUT_VENDOR)/etc/camera/quantize_mtk_0.00246_1800-360620_singleinput_bs1_1285.dla \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_params.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/svq_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/svq_cache \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/video_bokeh_apu_front_20210413.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/video_bokeh_apu_front_20210413.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/dualbokehsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/dualbokehsnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/frontbokehsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontbokehsnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/frontsinglesnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsinglesnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/frontsupernightsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsupernightsnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/manualsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/manualsnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/normalpreview.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/normalpreview.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/normalsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/normalsnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/satsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/satsnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/superhdsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/superhdsnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/superlowlightsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/superlowlightsnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/thirdpartysnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/thirdpartysnapshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/camera/xiaomi/uwsuperlowlightshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/uwsuperlowlightshot.json \
    vendor/xiaomi/xaga/proprietary/vendor/etc/cust_color.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/cust_color_36.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_36.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/cust_color_42.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_42.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/elliptic_sensor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic_sensor.xml \
    vendor/xiaomi/xaga/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/xiaomi/xaga/proprietary/vendor/etc/init/hw/init.project.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.project.rc \
    vendor/xiaomi/xaga/proprietary/vendor/etc/init/init.fmradio_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fmradio_drv.rc \
    vendor/xiaomi/xaga/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/misound_res.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/misound_res_headphone.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res_headphone.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/misound_res_spk.bin:$(TARGET_COPY_OUT_VENDOR)/etc/misound_res_spk.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/smartpa_param/tfa98xx_device.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/tfa98xx_device.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/smartpa_param/tfa98xx_ringtone.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/tfa98xx_ringtone.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/smartpa_param/tfa98xx_voice.bin:$(TARGET_COPY_OUT_VENDOR)/etc/smartpa_param/tfa98xx_voice.bin \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-4k.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-4k.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-class0.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-4k.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-4k.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-camera.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-class0.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-huanji.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-huanji.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-mgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-navigation.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-nolimits.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-per-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-per-camera.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-per-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-per-class0.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-per-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-per-navigation.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-per-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-per-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-per-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-per-video.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-phone.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-tgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-video.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-global-videochat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-global-videochat.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-hp-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-hp-mgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-hp-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-hp-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-huanji.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-huanji.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-4k.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-4k.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-camera.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-class0.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-huanji.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-huanji.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-mgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-navigation.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-nolimits.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-per-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-per-camera.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-per-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-per-class0.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-per-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-per-navigation.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-per-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-per-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-per-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-per-video.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-phone.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-tgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-video.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-india-videochat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-videochat.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-4k.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-4k.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-camera.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-class0.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-huanji.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-huanji.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-mgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-navigation.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-nolimits.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-per-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-per-camera.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-per-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-per-class0.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-per-huanji.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-per-huanji.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-per-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-per-navigation.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-per-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-per-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-per-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-per-video.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-phone.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-tgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-video.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-l16u-videochat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-l16u-videochat.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-map-global.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map-global.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-map-india.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map-india.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-map-l16u-cn.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map-l16u-cn.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-navigation.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-per-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-camera.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-per-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-class0.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-per-huanji.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-huanji.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-per-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-navigation.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-per-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-normal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-per-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-video.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-region-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-region-map.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal-videochat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-videochat.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/disable_skin_control.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_skin_control.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/disable_thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/disable_thermal_temp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal_temp.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/disable_throttling.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_throttling.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/thermal_mtbf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_mtbf.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/thermal_policy_00.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_00.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/thermal_policy_01.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_01.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/thermal_policy_02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_02.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/thermal_policy_03.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_03.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermal/thermal_policy_08.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_08.conf \
    vendor/xiaomi/xaga/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/aw8697_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8697_haptic.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/aw8697_rtp_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8697_rtp_1.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/lib3a.ccu_dummy:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu_dummy \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/novatek_nt36672e_l16_fw01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36672e_l16_fw01.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/novatek_nt36672e_l16_fw02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36672e_l16_fw02.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/novatek_nt36672e_l16_mp01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36672e_l16_mp01.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/novatek_nt36672e_l16_mp02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36672e_l16_mp02.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/novatek_ts_fw02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw02.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/novatek_ts_mp02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp02.bin \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/txpowerctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl.cfg \
    vendor/xiaomi/xaga/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/xiaomi/xaga/proprietary/vendor/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/libnfc-nxp_RF.conf \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/0102030405060708090a0b0c0d0e0f10.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/0102030405060708090a0b0c0d0e0f10.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/020f0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020f0000000000000000000000000000.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/06090000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/06090000000000000000000000000000.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/08010203000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08010203000000000000000000000000.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/08030000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08030000000000000000000000000000.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/08110000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08110000000000000000000000000000.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/40188311faf343488db888ad39496f9a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/40188311faf343488db888ad39496f9a.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/655a4b46cd7711eaaafbf382a6988e7b.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/fc32e4da17d342449b01c992d56d71bf.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/fc32e4da17d342449b01c992d56d71bf.ta \
    vendor/xiaomi/xaga/proprietary/vendor/thh/ta/isee_model.json:$(TARGET_COPY_OUT_VENDOR)/thh/ta/isee_model.json \
    vendor/xiaomi/xaga/proprietary/vendor_ramdisk/lib/firmware/novatek_nt36672e_l16_fw01.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/firmware/novatek_nt36672e_l16_fw01.bin \
    vendor/xiaomi/xaga/proprietary/vendor_ramdisk/lib/firmware/novatek_nt36672e_l16_fw02.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/firmware/novatek_nt36672e_l16_fw02.bin \
    vendor/xiaomi/xaga/proprietary/vendor_ramdisk/lib/firmware/novatek_nt36672e_l16_mp01.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/firmware/novatek_nt36672e_l16_mp01.bin \
    vendor/xiaomi/xaga/proprietary/vendor_ramdisk/lib/firmware/novatek_nt36672e_l16_mp02.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/firmware/novatek_nt36672e_l16_mp02.bin \
    vendor/xiaomi/xaga/proprietary/vendor_ramdisk/lib/firmware/novatek_ts_fw02.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/firmware/novatek_ts_fw02.bin \
    vendor/xiaomi/xaga/proprietary/vendor_ramdisk/lib/firmware/novatek_ts_mp02.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/firmware/novatek_ts_mp02.bin

PRODUCT_PACKAGES += \
    com.xiaomi.plugin.arcsoftsr \
    com.xiaomi.plugin.capbokeh \
    com.xiaomi.plugin.dc \
    com.xiaomi.plugin.depurple \
    com.xiaomi.plugin.hdr \
    com.xiaomi.plugin.ldc \
    com.xiaomi.plugin.memcpy \
    com.xiaomi.plugin.miaideblur \
    com.xiaomi.plugin.miaiie \
    com.xiaomi.plugin.mibokeh \
    com.xiaomi.plugin.mifragment \
    com.xiaomi.plugin.misegment \
    com.xiaomi.plugin.rawsuperlight \
    com.xiaomi.plugin.skinbeautifier \
    com.xiaomi.plugin.sr \
    com.xiaomi.plugin.superlowlight \
    com.xiaomi.plugin.supernight \
    com.xiaomi.plugin.swflip \
    com.xiaomi.plugin.tetrassr \
    audio.primary.mediatek \
    fingerprint.fpc.default \
    fingerprint.goodix.default \
    android.hardware.camera.provider@2.6-impl-mediatek \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    sensors.elliptic@2.0 \
    vendor.mediatek.hardware.camera.isphal@1.1-impl \
    lib3a.ae.pipe \
    lib3a.cculog \
    libAITrackingAFMgr \
    libArcNetMtk \
    libBasicModule \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSuperSensor \
    libSuperSensorCPU \
    libSuperSensorProcessor \
    lib_sr_models \
    libaaa_gma \
    libai_pq \
    libai_sdr2hdr \
    libai_sdr2hdr_auth \
    libaispq \
    libalCFR \
    libalhLDC \
    libanc_calibration_parser \
    libanc_dc_base \
    libanc_supervq \
    libarcbokeh.preview \
    libarcsoft_beautyshot \
    libarcsoft_distortion_correction \
    libarcsoft_dualcam_refocus_image \
    libarcsoft_dualcam_refocus_video \
    libarcsoft_hdr_detection \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_mf_superresolution \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_super_night_raw \
    libarcsoft_supernight \
    libaudio_param_parser-vnd \
    libbeauty_face_interface \
    libc++_shared \
    libcam.hal3a.guard \
    libcamalgo.WarpMapResizer \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.hdr10p \
    libcamalgo.lmv \
    libcamalgo.mcnr \
    libcamalgo.n3d \
    libcamalgo.platform \
    libcamalgo.utility \
    libcamalgo.vsdofUtil \
    libcamalgo.warp \
    libcamera_scene \
    libcameraplatforminfoxiaomi \
    libcamerasensorinfoxiaomi \
    libcom.xiaomi.metadatautils \
    libcom.xiaomi.pluginutils \
    libfeature.hdr10 \
    libfeaturepolicy \
    libfeaturepolicy_dbhandler \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libheichal \
    libimagebuffer_wrapper \
    libmiStereoFactoryRemapBasicLib \
    libmiStereoFactoryRemapLib \
    libmiai_deblur \
    libmiai_portraitsupernight \
    libmialgo_ie_capture \
    libmialgo_rfs \
    libmialgo_sd \
    libmialgo_utils \
    libmialgoengine \
    libmialgoengine2 \
    libmibokeh_845_video \
    libmibokeh_mt6873 \
    libminiui \
    libmisound \
    libmisoundcrossfade \
    libmpbase \
    libmtkcam_3rdcalibration \
    libmtkcam_thirdparty.customzone \
    libmtkisp_metadata_v2 \
    libnotifyaudiohal \
    libpixelflinger \
    librelight_only \
    libremosaic_wrapper \
    libremosaiclib \
    librgbwlightsensor \
    libsdk_sr \
    libvideofilter_only \
    libvidhance \
    libvidhance_active_ois \
    libvidhance_autozoom \
    libvidhance_dmbr \
    libvidhance_face_stabilizer \
    libvidhance_horizon_correction \
    libvidhance_ldc \
    libvidhance_stabilizer \
    libvidhance_super_stabilization \
    libvpu \
    libvpu5 \
    libwa_widelens_undistort \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.assist.models1d \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.aishutter \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.awbsync \
    lib3a.custom.ae \
    lib3a.flash \
    lib3a.flicker \
    lib3a.log \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    lib3a.stat \
    libAIODcore \
    libAIOTcore \
    libDBAccessor_ISP \
    libMtkMediaController \
    libSonyIMX519PdafWrapper \
    lib_bsscore \
    libaaa_afassist \
    libaaa_feature \
    libaaa_ltm \
    libaaa_ltmx \
    libaaa_tnc \
    libaaa_toneutil \
    libaiawb_fs \
    libaiawb_fs_model \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaicapturecore \
    libaidepth_tuning \
    libalgo.aosp.log \
    libapudcutils \
    libcam.3a_isp.utils \
    libcam.afmgr \
    libcam.chdr \
    libcam.feature_utils \
    libcam.fw_me_tcy \
    libcam.hal3a.afassitmgr \
    libcam.hal3a.cctsvr.v4l2 \
    libcam.hal3a.ctrl \
    libcam.hal3a.ircutdrv \
    libcam.hal3a.lensdrv \
    libcam.hal3a.log \
    libcam.hal3a.lscMgrApi \
    libcam.hal3a.oisdrv \
    libcam.hal3a.ozoomdrv \
    libcam.hal3a.policy \
    libcam.hal3a \
    libcam.hal3a.tofdrv \
    libcam.hal3a.utils \
    libcam.hal3a.v3.ae.v4l2 \
    libcam.hal3a.v3.ai3a_v4l2 \
    libcam.hal3a.v3.awb_v4l2 \
    libcam.hal3a.v3.cac.mgr.v4l2 \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.flash.v4l2 \
    libcam.hal3a.v3.flicker.v4l2 \
    libcam.hal3a.v3.ir.v4l2 \
    libcam.hal3a.v3.lsctbl.v4l2 \
    libcam.hal3a.v3.nvram.v4l2 \
    libcam.hal3a.v3.sensor.v4l2 \
    libcam.hal3a.v3.strobe \
    libcam.hal3a.v3.stt_v4l2 \
    libcam.hal3a.v3.tone.mgr.v4l2 \
    libcam.halisp.TopCtrlMgr \
    libcam.halisp.TuningDataProvider \
    libcam.halisp.TuningDataProviderFactory \
    libcam.halisp.imp.v4l2 \
    libcam.halisp.plugin \
    libcam.halisp.utils \
    libcam.halisp.v4l2 \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.isptuning.v4l2 \
    libcam.peripheralcontroller \
    libcam.tuningcachemgr \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam_ipc_hal3a_client \
    libcam_ipc_halisp_client \
    libcam_ipc_nvbuf_client \
    libcamalgo.BSSwrapper \
    libcamalgo.Mfbllwrapper \
    libcamalgo.aibc \
    libcamalgo.aibcwrapper \
    libcamalgo.aihdr \
    libcamalgo.ainr \
    libcamalgo.ais2.bss \
    libcamalgo.ais2.mfnr \
    libcamalgo.ais2.mstm \
    libcamalgo.ais2 \
    libcamalgo.bss \
    libcamalgo.fus \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.vaidepth \
    libcamalgo.vainr \
    libcamalgo.vsf \
    libcamera.custom.af_assist_buf_mgr \
    libcamera.custom.af_assist_buf_mgr_open \
    libcamera.custom.af_assist_mgr \
    libcamera.custom.af_assist_pdp \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_calibration.core \
    libcameracustom.camera_exif \
    libcameracustom.cfg_setting.core \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.imgsensor.core \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libccd \
    libeffecthal.base \
    libfeature.face \
    libfeature.fwmvp \
    libfeature.mcnr \
    libfeature.stereo.provider \
    libfeature.vainr.hal \
    libfeature.vsdof.3a_info_provider \
    libfeature.vsdof.hal \
    libfeature_eis \
    libfeature_fsc \
    libfeature_rss \
    libfeature_vrp \
    libfeatureiodrv_mem \
    libimgsys_adl \
    libimgsys_cmt \
    libimgsys_daemon \
    libimgsys_dip \
    libimgsys_drvcommon \
    libimgsys_gce \
    libimgsys_main \
    libimgsys_me \
    libimgsys_pqdip \
    libimgsys_sensor \
    libimgsys_system \
    libimgsys_taskhandler \
    libimgsys_tdrhal \
    libimgsys_traw \
    libimgsys_utils \
    libimgsys_v4l2 \
    libimgsys_wpe \
    libispfeature_mtkcam.v4l2 \
    liblpnr \
    libmfllcore \
    libmgr3a.adapt \
    libmtkcam.atmseventmgr \
    libmtkcam.debugwrapper \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.p2g \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof.wrapper \
    libmtkcam.logicalcaminfoprovider \
    libmtkcam.logicalmodule \
    libmtkcam_aie \
    libmtkcam_android_zslprocessor \
    libmtkcam_buffer_flush \
    libmtkcam_ca \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_camcontroller \
    libmtkcam_camcoordinator \
    libmtkcam_camctrl \
    libmtkcam_coredev \
    libmtkcam_custzone \
    libmtkcam_debugutils \
    libmtkcam_devicemgr \
    libmtkcam_diputils \
    libmtkcam_dma_map \
    libmtkcam_exif \
    libmtkcam_faceResultHandler \
    libmtkcam_grallocutils \
    libmtkcam_hal3a_provider \
    libmtkcam_hal_android_app_cbadaptor \
    libmtkcam_hal_android_common \
    libmtkcam_hal_android_device \
    libmtkcam_hal_android_provider \
    libmtkcam_hal_android_utils \
    libmtkcam_hal_core_app \
    libmtkcam_hal_core_app_cbadaptor \
    libmtkcam_hal_core_device \
    libmtkcam_hal_core_devicesessionpolicy \
    libmtkcam_hal_core_featurepolicy \
    libmtkcam_hal_core_provider \
    libmtkcam_hal_core_utils \
    libmtkcam_hal_custom \
    libmtkcam_hal_custom_provider \
    libmtkcam_hal_hidl_common \
    libmtkcam_hal_hidl_device \
    libmtkcam_hal_hidl_provider \
    libmtkcam_hal_hidl_utils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_hwutils_android \
    libmtkcam_hwutils_poweronoffcontroller \
    libmtkcam_imgbuf_v2 \
    libmtkcam_ipc_core \
    libmtkcam_ipc_wrapper_common_client \
    libmtkcam_ipc_wrapper_common_server \
    libmtkcam_ipc_wrapper_mtk_client \
    libmtkcam_ipc_wrapper_mtk_server \
    libmtkcam_jsonconvertor \
    libmtkcam_jsondata \
    libmtkcam_mapping_mgr \
    libmtkcam_metaconv \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_packutils \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_pipemgr \
    libmtkcam_postprocprovider \
    libmtkcam_prerelease \
    libmtkcam_proc \
    libmtkcam_request_requlator \
    libmtkcam_sensorcontrol \
    libmtkcam_simager \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_thirdparty.core \
    libmtkcam_thirdparty.customer \
    libmtkcam_thirdparty.mtk \
    libmtkcam_thirdparty \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcm_ipc_dummy \
    libpda_usdriver \
    libstereoinfoaccessor_vsdof \
    libvainr_model \
    mtk000_mipi_raw_IdxMgr \
    mtk000_mipi_raw_tuning \
    xagagc02m1_mipi_raw_3_IdxMgr \
    xagagc02m1_mipi_raw_3_tuning \
    xagagc02m1_mipi_raw_IdxMgr \
    xagagc02m1_mipi_raw_tuning \
    xagaov02b10_mipi_raw_3_IdxMgr \
    xagaov02b10_mipi_raw_3_tuning \
    xagaov02b10_mipi_raw_IdxMgr \
    xagaov02b10_mipi_raw_tuning \
    xagaov16a1_mipi_raw_2_IdxMgr \
    xagaov16a1_mipi_raw_2_tuning \
    xagaov16a1_mipi_raw_3_IdxMgr \
    xagaov16a1_mipi_raw_3_tuning \
    xagaov16a1_mipi_raw_4_IdxMgr \
    xagaov16a1_mipi_raw_4_tuning \
    xagaov16a1_mipi_raw_IdxMgr \
    xagaov16a1_mipi_raw_tuning \
    xagas5k4h7_mipi_raw_2_IdxMgr \
    xagas5k4h7_mipi_raw_2_tuning \
    xagas5k4h7_mipi_raw_3_IdxMgr \
    xagas5k4h7_mipi_raw_3_tuning \
    xagas5k4h7_mipi_raw_4_IdxMgr \
    xagas5k4h7_mipi_raw_4_tuning \
    xagas5k4h7_mipi_raw_IdxMgr \
    xagas5k4h7_mipi_raw_tuning \
    xagas5kgw1_mipi_raw_2_IdxMgr \
    xagas5kgw1_mipi_raw_2_tuning \
    xagas5kgw1_mipi_raw_3_IdxMgr \
    xagas5kgw1_mipi_raw_3_tuning \
    xagas5kgw1_mipi_raw_4_IdxMgr \
    xagas5kgw1_mipi_raw_4_tuning \
    xagas5kgw1_mipi_raw_IdxMgr \
    xagas5kgw1_mipi_raw_tuning \
    xagas5khm2_mipi_raw_3_IdxMgr \
    xagas5khm2_mipi_raw_3_tuning \
    xagas5khm2_mipi_raw_IdxMgr \
    xagas5khm2_mipi_raw_tuning \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.device@3.6 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    batterysecret \
    camerahalserver \
    mi_thermald

PRODUCT_PACKAGES += \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_ae_ParameterDB_ae_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_af_ParameterDB_af_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_awb_ParameterDB_awb_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_awbsync_ParameterDB_awbsync_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_feature_ParameterDB_feature_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_flash_ParameterDB_flash_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_flashcali_ParameterDB_flashcali_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_ParameterDB_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_top_control_data_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_pd_ParameterDB_pd_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_pipeline_ParameterDB_pipeline_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tone_ParameterDB_tone_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_default_sensor_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_default_sensor_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ISP_info_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagagc02m1_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagagc02m1_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagagc02m1_mipi_raw_3_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagagc02m1_mipi_raw_3_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov02b10_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov02b10_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov02b10_mipi_raw_3_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov02b10_mipi_raw_3_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov16a1_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov16a1_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov16a1_mipi_raw_2_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov16a1_mipi_raw_2_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov16a1_mipi_raw_3_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov16a1_mipi_raw_3_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov16a1_mipi_raw_4_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagaov16a1_mipi_raw_4_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5k4h7_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5k4h7_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5k4h7_mipi_raw_2_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5k4h7_mipi_raw_2_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5k4h7_mipi_raw_3_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5k4h7_mipi_raw_3_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5k4h7_mipi_raw_4_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5k4h7_mipi_raw_4_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5kgw1_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5kgw1_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5kgw1_mipi_raw_2_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5kgw1_mipi_raw_2_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5kgw1_mipi_raw_3_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5kgw1_mipi_raw_3_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5kgw1_mipi_raw_4_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5kgw1_mipi_raw_4_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5khm2_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5khm2_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5khm2_mipi_raw_3_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_xagas5khm2_mipi_raw_3_ISP_param_db \
    vendor_bin_hw_camerahalserver \
    vendor_lib64_hw_audio_primary_mt6895_so \
    vendor_lib64_hw_android_hardware_camera_provider@2_6-impl-mediatek_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_atms@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_bgservice@1_1-impl_so \
    vendor_lib64_lib3a_ae_core_so \
    vendor_lib64_lib3a_ae_so \
    vendor_lib64_lib3a_af_assist_models1d_so \
    vendor_lib64_lib3a_af_assist_so \
    vendor_lib64_lib3a_af_assist_utils_so \
    vendor_lib64_lib3a_af_core_so \
    vendor_lib64_lib3a_af_so \
    vendor_lib64_lib3a_aishutter_so \
    vendor_lib64_lib3a_alsflicker_so \
    vendor_lib64_lib3a_awb_core_so \
    vendor_lib64_lib3a_awbsync_so \
    vendor_lib64_lib3a_custom_ae_so \
    vendor_lib64_lib3a_flash_so \
    vendor_lib64_lib3a_flicker_so \
    vendor_lib64_lib3a_log_so \
    vendor_lib64_lib3a_sensors_color_so \
    vendor_lib64_lib3a_sensors_flicker_so \
    vendor_lib64_lib3a_stat_so \
    vendor_lib64_libAIODcore_so \
    vendor_lib64_libAIOTcore_so \
    vendor_lib64_libDBAccessor_ISP_so \
    vendor_lib64_libMtkMediaController_so \
    vendor_lib64_libSonyIMX519PdafWrapper_so \
    vendor_lib64_lib_bsscore_so \
    vendor_lib64_libaaa_afassist_so \
    vendor_lib64_libaaa_feature_so \
    vendor_lib64_libaaa_ltm_so \
    vendor_lib64_libaaa_ltmx_so \
    vendor_lib64_libaaa_tnc_so \
    vendor_lib64_libaaa_toneutil_so \
    vendor_lib64_libaiawb_fs_so \
    vendor_lib64_libaiawb_fs_model_so \
    vendor_lib64_libaiawb_moon_so \
    vendor_lib64_libaiawb_moon_model_so \
    vendor_lib64_libaiawb_p1ggm_so \
    vendor_lib64_libaiawb_sun_so \
    vendor_lib64_libaiawb_sun_model_so \
    vendor_lib64_libaibc_tuning_so \
    vendor_lib64_libaibc_tuning_p2_so \
    vendor_lib64_libaibc_tuning_p3_so \
    vendor_lib64_libaicapturecore_so \
    vendor_lib64_libaidepth_tuning_so \
    vendor_lib64_libalgo_aosp_log_so \
    vendor_lib64_libapudcutils_so \
    vendor_lib64_libcam_3a_isp_utils_so \
    vendor_lib64_libcam_afmgr_so \
    vendor_lib64_libcam_chdr_so \
    vendor_lib64_libcam_feature_utils_so \
    vendor_lib64_libcam_fw_me_tcy_so \
    vendor_lib64_libcam_hal3a_afassitmgr_so \
    vendor_lib64_libcam_hal3a_cctsvr_v4l2_so \
    vendor_lib64_libcam_hal3a_ctrl_so \
    vendor_lib64_libcam_hal3a_ircutdrv_so \
    vendor_lib64_libcam_hal3a_lensdrv_so \
    vendor_lib64_libcam_hal3a_log_so \
    vendor_lib64_libcam_hal3a_lscMgrApi_so \
    vendor_lib64_libcam_hal3a_oisdrv_so \
    vendor_lib64_libcam_hal3a_ozoomdrv_so \
    vendor_lib64_libcam_hal3a_policy_so \
    vendor_lib64_libcam_hal3a_so \
    vendor_lib64_libcam_hal3a_tofdrv_so \
    vendor_lib64_libcam_hal3a_utils_so \
    vendor_lib64_libcam_hal3a_v3_ae_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_ai3a_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_awb_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_cac_mgr_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_dng_so \
    vendor_lib64_libcam_hal3a_v3_flash_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_flicker_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_ir_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_lsctbl_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_nvram_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_sensor_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_strobe_so \
    vendor_lib64_libcam_hal3a_v3_stt_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_tone_mgr_v4l2_so \
    vendor_lib64_libcam_halisp_TopCtrlMgr_so \
    vendor_lib64_libcam_halisp_TuningDataProvider_so \
    vendor_lib64_libcam_halisp_TuningDataProviderFactory_so \
    vendor_lib64_libcam_halisp_imp_v4l2_so \
    vendor_lib64_libcam_halisp_plugin_so \
    vendor_lib64_libcam_halisp_utils_so \
    vendor_lib64_libcam_halisp_v4l2_so \
    vendor_lib64_libcam_halsensor_hwintegration_so \
    vendor_lib64_libcam_halsensor_so \
    vendor_lib64_libcam_isptuning_v4l2_so \
    vendor_lib64_libcam_peripheralcontroller_so \
    vendor_lib64_libcam_tuningcachemgr_so \
    vendor_lib64_libcam_utils_sensorprovider_so \
    vendor_lib64_libcam_vhdr_so \
    vendor_lib64_libcam_ipc_hal3a_client_so \
    vendor_lib64_libcam_ipc_halisp_client_so \
    vendor_lib64_libcam_ipc_nvbuf_client_so \
    vendor_lib64_libcamalgo_BSSwrapper_so \
    vendor_lib64_libcamalgo_Mfbllwrapper_so \
    vendor_lib64_libcamalgo_aibc_so \
    vendor_lib64_libcamalgo_aibcwrapper_so \
    vendor_lib64_libcamalgo_aihdr_so \
    vendor_lib64_libcamalgo_ainr_so \
    vendor_lib64_libcamalgo_ais2_bss_so \
    vendor_lib64_libcamalgo_ais2_mfnr_so \
    vendor_lib64_libcamalgo_ais2_mstm_so \
    vendor_lib64_libcamalgo_ais2_so \
    vendor_lib64_libcamalgo_bss_so \
    vendor_lib64_libcamalgo_fus_so \
    vendor_lib64_libcamalgo_lsc_so \
    vendor_lib64_libcamalgo_mfnr_so \
    vendor_lib64_libcamalgo_platform2_so \
    vendor_lib64_libcamalgo_rotate_so \
    vendor_lib64_libcamalgo_vaidepth_so \
    vendor_lib64_libcamalgo_vainr_so \
    vendor_lib64_libcamalgo_vsf_so \
    vendor_lib64_libcamera_custom_af_assist_buf_mgr_so \
    vendor_lib64_libcamera_custom_af_assist_buf_mgr_open_so \
    vendor_lib64_libcamera_custom_af_assist_mgr_so \
    vendor_lib64_libcamera_custom_af_assist_pdp_so \
    vendor_lib64_libcamera_customae_so \
    vendor_lib64_libcamera_customaf_so \
    vendor_lib64_libcamera_customawb_so \
    vendor_lib64_libcamera_customflk_so \
    vendor_lib64_libcameracustom_camera_3a_so \
    vendor_lib64_libcameracustom_camera_isp_so \
    vendor_lib64_libcameracustom_camera_sensors_so \
    vendor_lib64_libcameracustom_camera_calibration_core_so \
    vendor_lib64_libcameracustom_camera_exif_so \
    vendor_lib64_libcameracustom_cfg_setting_core_so \
    vendor_lib64_libcameracustom_eis_so \
    vendor_lib64_libcameracustom_flashlight_so \
    vendor_lib64_libcameracustom_imgsensor_core_so \
    vendor_lib64_libcameracustom_lens_so \
    vendor_lib64_libcameracustom_plugin_so \
    vendor_lib64_libcameracustom_so \
    vendor_lib64_libccd_so \
    vendor_lib64_libeffecthal_base_so \
    vendor_lib64_libfeature_face_so \
    vendor_lib64_libfeature_fwmvp_so \
    vendor_lib64_libfeature_mcnr_so \
    vendor_lib64_libfeature_stereo_provider_so \
    vendor_lib64_libfeature_vainr_hal_so \
    vendor_lib64_libfeature_vsdof_3a_info_provider_so \
    vendor_lib64_libfeature_vsdof_hal_so \
    vendor_lib64_libfeature_eis_so \
    vendor_lib64_libfeature_fsc_so \
    vendor_lib64_libfeature_rss_so \
    vendor_lib64_libfeature_vrp_so \
    vendor_lib64_libfeatureiodrv_mem_so \
    vendor_lib64_libimgsys_adl_so \
    vendor_lib64_libimgsys_cmt_so \
    vendor_lib64_libimgsys_daemon_so \
    vendor_lib64_libimgsys_dip_so \
    vendor_lib64_libimgsys_drvcommon_so \
    vendor_lib64_libimgsys_gce_so \
    vendor_lib64_libimgsys_main_so \
    vendor_lib64_libimgsys_me_so \
    vendor_lib64_libimgsys_pqdip_so \
    vendor_lib64_libimgsys_sensor_so \
    vendor_lib64_libimgsys_system_so \
    vendor_lib64_libimgsys_taskhandler_so \
    vendor_lib64_libimgsys_tdrhal_so \
    vendor_lib64_libimgsys_traw_so \
    vendor_lib64_libimgsys_utils_so \
    vendor_lib64_libimgsys_v4l2_so \
    vendor_lib64_libimgsys_wpe_so \
    vendor_lib64_libispfeature_mtkcam_v4l2_so \
    vendor_lib64_liblpnr_so \
    vendor_lib64_libmfllcore_so \
    vendor_lib64_libmgr3a_adapt_so \
    vendor_lib64_libmtkcam_atmseventmgr_so \
    vendor_lib64_libmtkcam_debugwrapper_so \
    vendor_lib64_libmtkcam_eventcallback_so \
    vendor_lib64_libmtkcam_featurepipe_capture_so \
    vendor_lib64_libmtkcam_featurepipe_depthmap_so \
    vendor_lib64_libmtkcam_featurepipe_p2g_so \
    vendor_lib64_libmtkcam_featurepipe_streaming_so \
    vendor_lib64_libmtkcam_featurepipe_vsdof_wrapper_so \
    vendor_lib64_libmtkcam_logicalcaminfoprovider_so \
    vendor_lib64_libmtkcam_logicalmodule_so \
    vendor_lib64_libmtkcam_aie_so \
    vendor_lib64_libmtkcam_android_zslprocessor_so \
    vendor_lib64_libmtkcam_buffer_flush_so \
    vendor_lib64_libmtkcam_ca_so \
    vendor_lib64_libmtkcam_calibration_convertor_so \
    vendor_lib64_libmtkcam_calibration_provider_so \
    vendor_lib64_libmtkcam_camcontroller_so \
    vendor_lib64_libmtkcam_camcoordinator_so \
    vendor_lib64_libmtkcam_camctrl_so \
    vendor_lib64_libmtkcam_coredev_so \
    vendor_lib64_libmtkcam_custzone_so \
    vendor_lib64_libmtkcam_debugutils_so \
    vendor_lib64_libmtkcam_devicemgr_so \
    vendor_lib64_libmtkcam_diputils_so \
    vendor_lib64_libmtkcam_dma_map_so \
    vendor_lib64_libmtkcam_exif_so \
    vendor_lib64_libmtkcam_faceResultHandler_so \
    vendor_lib64_libmtkcam_grallocutils_so \
    vendor_lib64_libmtkcam_hal3a_provider_so \
    vendor_lib64_libmtkcam_hal_android_app_cbadaptor_so \
    vendor_lib64_libmtkcam_hal_android_common_so \
    vendor_lib64_libmtkcam_hal_android_device_so \
    vendor_lib64_libmtkcam_hal_android_provider_so \
    vendor_lib64_libmtkcam_hal_android_utils_so \
    vendor_lib64_libmtkcam_hal_core_app_so \
    vendor_lib64_libmtkcam_hal_core_app_cbadaptor_so \
    vendor_lib64_libmtkcam_hal_core_device_so \
    vendor_lib64_libmtkcam_hal_core_devicesessionpolicy_so \
    vendor_lib64_libmtkcam_hal_core_featurepolicy_so \
    vendor_lib64_libmtkcam_hal_core_provider_so \
    vendor_lib64_libmtkcam_hal_core_utils_so \
    vendor_lib64_libmtkcam_hal_custom_so \
    vendor_lib64_libmtkcam_hal_custom_provider_so \
    vendor_lib64_libmtkcam_hal_hidl_common_so \
    vendor_lib64_libmtkcam_hal_hidl_device_so \
    vendor_lib64_libmtkcam_hal_hidl_provider_so \
    vendor_lib64_libmtkcam_hal_hidl_utils_so \
    vendor_lib64_libmtkcam_hwnode_so \
    vendor_lib64_libmtkcam_hwutils_so \
    vendor_lib64_libmtkcam_hwutils_android_so \
    vendor_lib64_libmtkcam_hwutils_poweronoffcontroller_so \
    vendor_lib64_libmtkcam_imgbuf_v2_so \
    vendor_lib64_libmtkcam_ipc_core_so \
    vendor_lib64_libmtkcam_ipc_wrapper_common_client_so \
    vendor_lib64_libmtkcam_ipc_wrapper_common_server_so \
    vendor_lib64_libmtkcam_ipc_wrapper_mtk_client_so \
    vendor_lib64_libmtkcam_ipc_wrapper_mtk_server_so \
    vendor_lib64_libmtkcam_jsonconvertor_so \
    vendor_lib64_libmtkcam_jsondata_so \
    vendor_lib64_libmtkcam_mapping_mgr_so \
    vendor_lib64_libmtkcam_metaconv_so \
    vendor_lib64_libmtkcam_metadata_so \
    vendor_lib64_libmtkcam_metastore_so \
    vendor_lib64_libmtkcam_modulefactory_custom_so \
    vendor_lib64_libmtkcam_modulefactory_utils_so \
    vendor_lib64_libmtkcam_modulehelper_so \
    vendor_lib64_libmtkcam_packutils_so \
    vendor_lib64_libmtkcam_pipeline_so \
    vendor_lib64_libmtkcam_pipeline_fbm_so \
    vendor_lib64_libmtkcam_pipelinemodel_capture_so \
    vendor_lib64_libmtkcam_pipelinemodel_session_so \
    vendor_lib64_libmtkcam_pipelinemodel_utils_so \
    vendor_lib64_libmtkcam_pipelinepolicy-security_so \
    vendor_lib64_libmtkcam_pipelinepolicy-smvr_so \
    vendor_lib64_libmtkcam_pipelinepolicy_so \
    vendor_lib64_libmtkcam_pipelinepolicy_factory_so \
    vendor_lib64_libmtkcam_pipemgr_so \
    vendor_lib64_libmtkcam_postprocprovider_so \
    vendor_lib64_libmtkcam_prerelease_so \
    vendor_lib64_libmtkcam_proc_so \
    vendor_lib64_libmtkcam_request_requlator_so \
    vendor_lib64_libmtkcam_sensorcontrol_so \
    vendor_lib64_libmtkcam_simager_so \
    vendor_lib64_libmtkcam_stdutils_so \
    vendor_lib64_libmtkcam_streamutils_so \
    vendor_lib64_libmtkcam_synchelper_so \
    vendor_lib64_libmtkcam_sysutils_so \
    vendor_lib64_libmtkcam_thirdparty_core_so \
    vendor_lib64_libmtkcam_thirdparty_customer_so \
    vendor_lib64_libmtkcam_thirdparty_mtk_so \
    vendor_lib64_libmtkcam_thirdparty_so \
    vendor_lib64_libmtkcam_tuning_utils_so \
    vendor_lib64_libmtkcam_ulog_so \
    vendor_lib64_libmtkcm_ipc_dummy_so \
    vendor_lib64_libpda_usdriver_so \
    vendor_lib64_libstereoinfoaccessor_vsdof_so \
    vendor_lib64_libvainr_model_so \
    vendor_lib64_mtk000_mipi_raw_IdxMgr_so \
    vendor_lib64_mtk000_mipi_raw_tuning_so \
    vendor_lib64_xagagc02m1_mipi_raw_3_IdxMgr_so \
    vendor_lib64_xagagc02m1_mipi_raw_3_tuning_so \
    vendor_lib64_xagagc02m1_mipi_raw_IdxMgr_so \
    vendor_lib64_xagagc02m1_mipi_raw_tuning_so \
    vendor_lib64_xagaov02b10_mipi_raw_3_IdxMgr_so \
    vendor_lib64_xagaov02b10_mipi_raw_3_tuning_so \
    vendor_lib64_xagaov02b10_mipi_raw_IdxMgr_so \
    vendor_lib64_xagaov02b10_mipi_raw_tuning_so \
    vendor_lib64_xagaov16a1_mipi_raw_2_IdxMgr_so \
    vendor_lib64_xagaov16a1_mipi_raw_2_tuning_so \
    vendor_lib64_xagaov16a1_mipi_raw_3_IdxMgr_so \
    vendor_lib64_xagaov16a1_mipi_raw_3_tuning_so \
    vendor_lib64_xagaov16a1_mipi_raw_4_IdxMgr_so \
    vendor_lib64_xagaov16a1_mipi_raw_4_tuning_so \
    vendor_lib64_xagaov16a1_mipi_raw_IdxMgr_so \
    vendor_lib64_xagaov16a1_mipi_raw_tuning_so \
    vendor_lib64_xagas5k4h7_mipi_raw_2_IdxMgr_so \
    vendor_lib64_xagas5k4h7_mipi_raw_2_tuning_so \
    vendor_lib64_xagas5k4h7_mipi_raw_3_IdxMgr_so \
    vendor_lib64_xagas5k4h7_mipi_raw_3_tuning_so \
    vendor_lib64_xagas5k4h7_mipi_raw_4_IdxMgr_so \
    vendor_lib64_xagas5k4h7_mipi_raw_4_tuning_so \
    vendor_lib64_xagas5k4h7_mipi_raw_IdxMgr_so \
    vendor_lib64_xagas5k4h7_mipi_raw_tuning_so \
    vendor_lib64_xagas5kgw1_mipi_raw_2_IdxMgr_so \
    vendor_lib64_xagas5kgw1_mipi_raw_2_tuning_so \
    vendor_lib64_xagas5kgw1_mipi_raw_3_IdxMgr_so \
    vendor_lib64_xagas5kgw1_mipi_raw_3_tuning_so \
    vendor_lib64_xagas5kgw1_mipi_raw_4_IdxMgr_so \
    vendor_lib64_xagas5kgw1_mipi_raw_4_tuning_so \
    vendor_lib64_xagas5kgw1_mipi_raw_IdxMgr_so \
    vendor_lib64_xagas5kgw1_mipi_raw_tuning_so \
    vendor_lib64_xagas5khm2_mipi_raw_3_IdxMgr_so \
    vendor_lib64_xagas5khm2_mipi_raw_3_tuning_so \
    vendor_lib64_xagas5khm2_mipi_raw_IdxMgr_so \
    vendor_lib64_xagas5khm2_mipi_raw_tuning_so
